export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_SPECIFIC_CATEGORIES = "GET_SPECIFIC_CATEGORIES";
export const GET_ALL_CARTS = "GET_ALL_CARTS";
export const POST_CART = "POST_CART";